---
title: "Assignment2"
author: "LingzhouAo"
date: "2/24/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic_R_Exercise_2
### 1
```{r}
A <- matrix(c(1,1,3,5,2,6,-2,-1,-3), nrow = 3, byrow = TRUE)
A
A^3
A[,3] <- A[,2] + A[,3]
A
```
### 2
```{r}
B <- matrix(c(10,-10,10),nrow = 15, ncol = 3 ,byrow=TRUE)
B
crossprod(B,B)
```
### 3
```{r}
matE <- matrix(rep(0,36), nrow = 6, byrow = TRUE)
row(matE)
col(matE)
row(matE)-col(matE)
matE[abs(row(matE)-col(matE))==1] <- 1
matE
```
### 4
```{r}
a <- 0:4
A <- outer(a,a,"+")
A
B <- outer(a,a, "*")
B
b <- 5:10
C <- outer(a,b,"+")
C
D <- outer(b,a, "%%")
D
```
### 5
```{r}
a <- 0:4
A <- outer(a,a,"+")%%5
A
b <- 0:9
B <- outer(b,b,"+")%%10
B
c <- 0:8
C <- outer(c, c, "-")%%9
C
```
### 6
```{r}
A <- matrix(c(1,2,3,4,5,2,1,2,3,4,3,2,1,2,3,4,3,2,1,2,5,4,3,2,1),nrow = 5, ncol = 5,byrow=TRUE)
A
y <- matrix(c(7,-1,-3,5,17),nrow = 5, ncol = 1, byrow=TRUE)
y
x <- solve(A) %*% y
x
```
### 7
```{r}
set.seed(75)
aMat <- matrix(sample(10, size=60, replace=TRUE), nr=6)
aMat
apply(aMat, 1, function(x){sum(x > 4)})

apply(aMat, 1, function(x){sum(x>6 & x <8)} == 2)

cSums <- colSums(aMat)
which( outer(cSums, cSums, "+") > 75, arr.ind = TRUE)
```
### 8
```{r}
sum((1:20)^4) * sum(1/(3+(1:5)))
```

##R_Function
###1a
```{r}
tmpFn1 <- function(xVec){
  return(xVec^(1:length(xVec)))
}
tmpFn2 <- function(xVec){
  return(xVec^(1:length(xVec))/(1:length(xVec)))
}
```
###1b
```{r}
tmpFn3 <- function(x, n){
  return(1+sum(x^(1:n)/(1:n)))
}
```
###2
```{r}
tmpFn <- function(xVec){
  return((xVec[-c(length(xVec)-1,length(xVec))] + xVec[-c(1,length(xVec))] + xVec[-c(1,2)])/3)
}

tmpFn(c(1:5,6:1))
```
###3
```{r}
tmpFn <- function(x){
  if (x < 0){
    return (x^2+2*x+3)
  }
  else if (x<2){
    return (x+3)
  }
  else{
    return (x^2+4*x-7)
  }
}
x <- seq(-3,3)
plot(x, tmpFn(x), type="l")
```
###4
```{r}
tmpFn <- function(mat){
  mat[mat%%2 == 1] <- 2 * mat[mat%%2 == 1]
  return(mat)
}
```
###5
```{r}
tmpFn <- function(n,k){
  tmp <- diag(k, nr = n)
  tmp[abs(row(tmp) - col(tmp)) == 1] <- 1
  return(tmp)
}
```
###6
```{r}
quadrant <- function(alpha){
  return(1 + (alpha%%360)%/%90)
}
```
###7
```{r}
weekday <- function(day,month,year){
  if ((month - 2) > 0){
    month <- month - 2
  }
  else{
    month <- month + 10
    year <- year - 1
  }
  cc <- year %/% 100
  year <- year %% 100
  tmp <- floor(2.6*month - 0.2) + day + year + year %/% 4 + cc %/% 4 - 2 * cc
  return(c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday")[1+tmp%%7])
}
```
###8a
```{r}
testLoop <- function(n){
  xVec <- rep(NA,n-1)
  for (i in 1:(n-1)){
    if (i == 1){
      xVec[i] = 1
    }
    else if (i == 2){
      xVec[i] == 2
    }
    else{
      xVec[i] = xVec[i-1] + (2 / xVec[i])
    }
  }
  return(xVec)
}
```
###8b
```{r}
testLoop2 <- function(yVec){
  return(sum(exp(seq(along=yVec))))
}
testLoop2(1:3)
```
###9a
```{r}
quadmap <- function(start, rho, niter){
  xVec <- rep(NA,niter)
  xVec[1] <- start
  for (i in 1:(niter-1)){
    xVec[i+1] <- rho*xVec[i]*(1 - xVec[i])
  }
  return(xVec)
}

tmp <- quadmap(start=0.95, rho=2.99, niter=500)
plot(tmp, type="l")
plot(tmp[300:500], type="l")
```
###9b
```{r}
quadmap2 <- function(start, rho){
  n <- 0
  pre <- start
  while(TRUE){
    now <- rho*pre*(1 - pre)
    n = n + 1
    if (abs(now - pre) < 0.02){
      break
    }
    pre <- now
  }
  return(n)
}
tmp2 <- quadmap2(start=0.95, rho=2.99)
tmp2
```
###10a
```{r}

tmpFn <- function(xVec){
  new_xVec <- xVec - mean(xVec)
  d <- sum(new_xVec^2)
  n <- length(xVec)
  r1 <- sum(new_xVec[2:n] * new_xVec[1:(n-1)])/d
  r2 <- sum(new_xVec[3:n] * new_xVec[1:(n-2)])/d
  return(c(r1,r2))
}
tmpFn(seq(2,56,by=3))
```
###10b
```{r}
tmpFn2 <- function(xVec, k){
  new_xVec <- xVec - mean(xVec)
  d <- sum(new_xVec^2)
  n <- length(xVec)
  temp <- function(j){
    sum(new_xVec[(j+1):n] * new_xVec[1:(n-j)] )/d
  }
  return(c(1, sapply(1:k, temp)))
}
```