---
title: "Assignment1"
author: "LingzhouAo"
date: "2/23/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Exercise 1
### 1
```{r}
a <- c(1:20)
a
```
```{r}
b <- c(20:1)
b
```
```{r}
c <- c(1:20,19:1)
c
```
```{r}
temp <- c(4,6,3)
temp
```
```{r}
temp_e <- rep(temp,times=10)
temp_e
```
```{r}
temp_f <- c(temp_e,4)
temp_f
```
```{r}
temp_g <- c(rep(temp_e[1],times=10), rep(temp_e[2],times=20), rep(temp_e[3],times=30))
temp_g
```
### 2
```{r}
x <- seq(3, 6, by=0.1)
y <- exp(x)*cos(x)
x
y
```
### 3
```{r}
a3 <-(0.1^seq(3,36, by=3))*(0.2^seq(1,34, by=3))
a3
```
```{r}
b3 <-(2^seq(1,25)/seq(1,25))
b3
```
### 4
```{r}
i <- seq(10,100)
a4 <- i^3+4*i^2
a4
```
```{r}
i <- seq(1,25)
b4 <- (2^i)/i+(3^i)/(i^2)
b4
```
### 5
```{r}
labels <- paste("label",1:30,sep=" ")
labels
```
```{r}
fns <- paste("fn",1:30,sep="")
fns
```
### 6
```{r}
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
```
```{r}
a6 <- yVec[-1]- xVec[-length(xVec)]
a6
```
```{r}
b6 <- sin(yVec[-length(yVec)])/cos(xVec[-1])
b6
```
```{r}
c6 <- xVec[-c(249,250)] + 2*xVec[-c(1,250)] - xVec[-c(1,2)]
c6
```
```{r}
d6 <- sum(exp(-xVec[-1])/(xVec[-length(xVec)] + 10))
d6
```
### 7
```{r}
a7 <- yVec[yVec>600]
a7
```
```{r}
b7 <- (1:length(yVec))[yVec > 600]
b7
```
```{r}
c7 <- xVec[yVec>600]
c7
```
```{r}
d7 <- sqrt(abs(xVec - mean(xVec)))
d7
```
```{r}
e7 <- sum(yVec > max(yVec) - 200)
e7
```
```{r}
f7 <- sum(xVec%%2 == 0)
f7
```
```{r}
g7 <-  xVec[order(yVec)]
g7
```
```{r}
h7 <- yVec[c(T,F,F)]
h7
```
### 8
```{r}
ans <- 1 + sum(cumprod(seq(2, 38, by = 2)/seq(3, 39, by = 2)))
ans
```


